---
abstract: 'Type constraints for LibXML classes'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-XML-LibXML
requires:
  English: 0
  Modern::Perl: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::URI: 0
  Path::Class: 0
  URI: 0
  XML::LibXML: 0
  namespace::autoclean: 0
  perl: 5.010
  utf8: 0
resources:
  bugtracker: https://github.com/mjgardner/moosex-types-xml-libxml/issues
  repository: git://github.com/mjgardner/moosex-types-xml-libxml.git
version: 0.001
